### ISSUE TITLE
Running "bulk-decaffeinate" outside of the project root fails to find "decaffeinate"

### ISSUE THREAD

**Issue by laurence-myers** [decaffeinate/bulk-decaffeinate#144]
Looks like the "node_modules" directory is looked up from the current working directory.

    nodeModulesPath = './node_modules/.bin/' + binaryName;

So, given a root path `myProject`, with sub-directory `app`, running "bulk-decaffeinate" from `myProject/app` will fail saying "decaffeinate binary not found on the PATH or in node_modules."

Maybe a lib like [get-installed-path](https://www.npmjs.com/package/get-installed-path) could help?

**Comment by alangpierce** [comment]
Thanks for reporting! In your case, I'd recommend running `bulk-decaffeinate check -d app` from the project root, rather than using a different working directory. It's not just the decaffeinate binary; `bulk-decaffeinate.config.js` and all git operations rely on the working directory, so I'd recommend always running the tool from the project root. For actual conversions, the way I've actually done it is to generate the files I want to convert as `filesToProcess` in the config file, then just convert those.

Happy to discuss alternate solutions, though. I certainly wouldn't object to something like get-installed-path, although from a quick read-through of the docs, it looks like you need to explicitly pass `cwd` to get binaries from parent `node_modules` directories; it won't search the directory ancestry in the same way that node's `require` does. (I might be misinterpreting the docs, though.)

Also note that you could just install decaffeinate (and eslint) globally instead of in node_modules. I ended up doing that at my company so that other developers wouldn't need to pull in dependencies that they don't end up using, and to make it easier to update decaffeinate.

**Comment by laurence-myers** [comment]
Thanks for your response! :slightly_smiling_face: 

I actually ended up writing a custom Windows batch script:
https://gist.github.com/laurence-myers/b36b0337a0e13e262a4076af63a66d4b

That script fulfilled my needs. I imagine the way I tried to use this tool was an unusual scenario, so I'm going to close this issue.

Thanks for decaffeinate, it's great! :grin:
